[package]
name = "graphics_lab"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22.0" # Используем eframe как основную библиотеку
egui = "0.22.0"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }